### ISSUE TITLE
侦听后程序就退出了

### ISSUE THREAD

**Issue by hezhiqiang** [Plen-wang/rabbitmqclient#1]
我在程序的Main函数中写了下列语句：
            RabbitMqClient.Instance.ActionEventMessage += mqClient_ActionEventMessage;
            RabbitMqClient.Instance.OnListening();
原本以为在OnListening时程序不会退出，结果是自动退出了，如果实现侦听消息程序不退出？

**Comment by Plen-wang** [comment]
如果是客户端程序你需要处理这个问题。如果是web程序就不需要处理这个问题。
因为主线程什么时候退出是根据宿主环境需求来的，处理起来都很简单。
